<?php

#print debug info?
$bDebug=false;

#the root for data files (wikipedia archives and index files). Expected structure is:
# $datapath
#     |- $lang (en, fr...)
#          |- db    (index files for the search engine, generated by the perl script)
#          |- bz2   (bz2 archives downloaded from download.wikimedia.org and split with bzip2recover - done by the perl script)


$conf=0;


$config[0]{"perlcmd"}    = "/opt/iphone/bin/perl";
$config[0]{"datapath"}   = "/private/var/root/Library/WebServer/Data";
$config[0]{"bzcmd"}      = "/var/root/bin/bzcat";
$config[0]{"parserpath"} = "w2h.pl";

$config[1]{"perlcmd"}    = "perl";
$config[1]{"datapath"}   = "D:/dev/iphonepedia";
$config[1]{"bzcmd"}      = "bzcat";
$config[1]{"parserpath"} = "w2h.pl";


?>